Auto Connection to chatroom and saving messages to database (basic)
UNLV-CS472-672/2024-S-GROUP4-SMTK pull request #159
Opened 2024-04-14 02:06 UTC by jusasin

### Title - Auto Connection and Saving Messages to Database
### Issue Number #144 
### Description 
Adding more functionality to the chatroom, which includes an auto connection to the chatroom so that the user does not need to press connect anymore when accessing the chatroom. Authored by Warren, messageSave.js includes saving messages to the database. At the moment there is only one chatroom that shows all messages and does not currently separate the chatrooms into user to user base. We also can not save the messages to specific users and reload those messages to the chat page because we need protected routes in order to get the correct session id from each user. 
### Testing
Assigned to Johnson and will be addressed. 
### Possible Errors
No known possible errors besides the functionality is a bit wonky, will be worked on more to what we imagined once we can use the cookies properly to get session ids.

2024-04-14 03:22 UTC, 39otsu approved these changes
Beautiful quality of life update. This will improve user experience by a ton

2024-04-14 21:15 UTC, blake-gilmore commented on chatroom-socket-server/server.js
>      socket.emit("users", users);
If this is building a list of users every time someone connects, we might be able to have a global users list that we would just add and remove from on each connect or disconnect

2024-04-14 21:17 UTC, blake-gilmore requested changes
Just needs adjustment for the test file to make sure the tests are still passing. Also will need to fix the merge conflict then I think it's ready. Not sure if there are any differences here in the chat page than the PR that we just merged from Jun, so I think that's worth looking over again.

2024-04-15 06:28 UTC, junxjr commented on small-talk/app/chat/page.js
> +		handleConnectButtonClick();
This is great, we had to use the connect button before, but it is so much easier and nicer to have an automatic connection.

2024-04-15 06:30 UTC, junxjr approved these changes
Everything looks good. The automatic connection works. I didn't try the saving message part on my end since I didn't connect to the mongodb yet. The next step would be solving the individual rooms issue and take a look at the useEffect connection.

2024-04-15 15:59 UTC, blake-gilmore commented on small-talk/app/chat/page.js
> +	}, [privateMessages]);
Will this reconnect on every private message change?

2024-04-16 00:18 UTC, jusasin commented
Currently commented out the test cases because there is more work being done and we plan to make the test cases better once the chatroom is more finalized. Lowered the test coverage as well to help with the continuation of work. Also began implementing the rooms aspect so that each user has their own room that another user can join.

2024-04-16 04:57 UTC, AlvaroH2001 commented
Merging this since it's met the approval numbers.

2024-04-16 04:57 UTC, merged

2024-04-16 17:54 UTC, aiharc1 reviewed
Looks good nice work with the automatic connection to the server and saving messages