Updated Current Homepage to Conceptual Homepage Theme
UNLV-CS472-672/2024-S-GROUP4-SMTK pull request #40
Opened 2024-02-27 03:21 UTC by Redblaze74

- Changed README.md to redirect to main repository PDF in case of future updates of PDF
- Separated page.js stylizations into styles.css 
- Refined and added more code into both page.js and styles.css
- Included necessary icons and temporary images that will be used for other pages

2024-02-27 03:42 UTC, aiharc1 approved these changes
Nice work Alec. The basic fundamentals of page transitions are there

2024-02-27 03:43 UTC, jusasin approved these changes
The added functionality is a huge help, now we can work on adding design to the different features of the website. Great work!

2024-02-28 07:09 UTC, junxjr approved these changes
Everything looks great. I like the designs.

2024-03-01 02:08 UTC, blake-gilmore requested changes

2024-03-01 02:08 UTC, blake-gilmore commented on small-talk/app/homepage/page.js
> +                <HoverButton onClick={handleRedirect('/game')} iconImage="/img/games-tab.png" altText="Games" />
Would love if we could implement a <menuButton> custom component that can take a list of redirects, icon image paths, and altText strings and map the list to a series of menu buttons. Then we can be sure to map that within a sidebar custom component as well to separate the functionality easier.

2024-03-01 02:08 UTC, blake-gilmore commented on small-talk/app/homepage/page.js
> +            </div>
Currently shows in the vercel deployment:
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP4-SMTK/assets/80655017/ebcd4c99-fb11-434c-9d5d-13ee3cc2f644)


To help debug this, when I zoom out I see:
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP4-SMTK/assets/80655017/757213c2-acbc-4c7c-86e6-99f932f65578)

And when I zoom in, I see:
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP4-SMTK/assets/80655017/96b62c05-60b9-4b9d-92f9-a1d06d814305)

2024-03-04 18:39 UTC, blake-gilmore commented on small-talk/app/homepage/page.js
> +                <HoverButton onClick={handleRedirect('/game')} iconImage="/img/games-tab.png" altText="Games" />
This is being handled in issue #52

2024-03-04 18:45 UTC, blake-gilmore commented on small-talk/app/homepage/page.js
> +            </div>
Looks good
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP4-SMTK/assets/80655017/1a06cdf6-77b0-486a-97a0-c4ee4c36764c)

2024-03-04 18:45 UTC, blake-gilmore approved these changes

2024-03-04 18:46 UTC, blake-gilmore commented
Looks great. Closes issue #10

2024-03-04 18:46 UTC, merged